
# 设置数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.206.128:3306/mall?characterEncoding=utf-8&useSSL=false
    username: root
    password: 100322

# 配置mapper.xml文件的位置
mybatis:
  mapper-locations: classpath:mappers/*.xml