
# 设置数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: 100322
  redis:
    host: 192.168.206.128
    port: 6380

# 配置mapper.xml文件的位置
mybatis:
  mapper-locations: classpath:mappers/*.xml
